//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sicil
    {
        public Sicil()
        {
            this.vatandas = new HashSet<vatanda>();
        }
    
        public int sicil_no { get; set; }
        public string sicil_no_suc { get; set; }
    
        public virtual ICollection<vatanda> vatandas { get; set; }
    }
}
