//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class vatanda
    {
        public int vatandas_id { get; set; }
        public string vatandas_tc { get; set; }
        public string vatandas_adsaoyad { get; set; }
        public Nullable<System.DateTime> vatandas_dogumgunu { get; set; }
        public string vatandas_cinsiyet { get; set; }
        public string vatandas_sicil { get; set; }
        public Nullable<int> sicil_no { get; set; }
    
        public virtual Sicil Sicil { get; set; }
    }
}
